from rdkit import Chem
import numpy as np
import pandas as pd
import argparse
from collections import Counter
import matplotlib.pyplot as plt
from rdkit.Chem import ChemicalFeatures
from rdkit import RDConfig
import os

# https://arxiv.org/abs/2107.02270 Petroff, Accessible Color Sequences for Data Visualization
c = ["#3f90da", "#ffa90e", "#bd1f01", "#94a4a2", "#832db6", "#a96b59", "#e76300", "#b9ac70", "#717581", "#92dadd"]

parser = argparse.ArgumentParser(description='Get pharmacophore features from a set of ligands')
parser.add_argument('--ph4', required=True, help='Input PH4 file')
parser.add_argument('--sdf', required=True, help='Input SDF file')
parser.add_argument('--center_txt', default='center.txt', help='CSV format x,y,z file of center')
parser.add_argument('--features_dat', required=True, help='Input silcs-style features.dat file with FGFE')
parser.add_argument('--out', default='./', help='Output directory; default = %(default)s')
parser.add_argument('--cutoff', default=2., type=float, help='Distance cutoff between atom and feature')
parser.add_argument('--n_feat', default=None, type=int, help='Number of features to output per hypothesis (exact match)')
parser.add_argument('--pad',  default=0., type=float, help='Pad feature radius (Ang); default=%(default)s')
parser.add_argument('--quiet', action='store_true', help='for ax0.show()')
args = parser.parse_args()

def parse_ph4(filename, features_dat=None):
  feature_rows = []

  n_features = None
  reading_features = False
  features_read = 0

  with open(filename, 'r') as f:
    for line in f:
      stripped = line.strip()

      # all the initial lines before #feature is read are part of the header
      if stripped.startswith("#feature"):
        parts = stripped.split()
        n_features = int(parts[1])
        reading_features = True
        continue

      if reading_features and features_read < n_features:
        if not stripped or stripped.startswith("#"): continue

        parts = stripped.split()
        # based on example format
        feature_rows.append({
          "type": parts[0],
          "color": parts[1],
          "x": float(parts[2]),
          "y": float(parts[3]),
          "z": float(parts[4]),
          "radius": float(parts[5]),
          "ebits": int(parts[6]),
          "gbits": int(parts[7]),
        })
        features_read += 1

      if reading_features and features_read == n_features: break

  features_df = pd.DataFrame(feature_rows)

  if features_dat:
    # Read in <prot>.features.dat file with the FGFE for each feature
    # Type | Sphere Center X | Y | Z | Sphere radius R | FGFE

    feat_dat = pd.read_csv(features_dat, sep='\\s+', skiprows=2, names=['Type','X','Y','Z','Radius','FGFE'])
    if feat_dat.shape[0] == features_df.shape[0]:
      features_df['FGFE'] = feat_dat['FGFE'].copy()
    else:
      print(f'Although {features_dat} was supplied, the number of features do not match {filename}')
 
  return features_df

def write_ph4(filename, features_df):
  n_features = str(features_df.shape[0])
  header = [
  "#moe:ph4que 2011.1\n",
  "#SILCS pharmacophore hypothesis generated by ph4gen utility\n",
  "#pharmacophore 5 tag t value *\n",
  f"scheme t Unified matchsize i  {n_features} title t $ comment s $ smask i 476156\n",
  f"#feature {n_features} expr tt color ix x r y r z r r r ebits ix gbits ix\n"
  ]

  with open(filename, "w") as f:
    # write header as-is
    for line in header:
      f.write(line)
    # write features
    for _, row in features_df.iterrows():
      f.write(
        f"{row['type']:12s} "
        f"{row['color']:6s} "
        f"{row['x']:10.4f} "
        f"{row['y']:10.4f} "
        f"{row['z']:10.4f} "
        f"{row['radius']:6.3f} "
        f"{int(row['ebits'])} "
        f"{int(row['gbits'])}\n"
      )
    f.write("#endpharmacophore\n")

features_df = parse_ph4(args.ph4, features_dat=args.features_dat)

# 'Donor', 'Acceptor', 'PosIonizable', 'NegIonizable', 'Aromatic', 'Hydrophobe', 'LumpedHydrophobe'
def rdkit_type(x):
  simple = []
  # determined that we want Aro|Hyd to simply have ['Aro', 'Hyd']
  ##if   ('Aro' in x) and ('Hyd' in x):       simple.append('LumpedHydrophobe') 
  if ('Aro' in x):                        simple.append('Aromatic')
  if ('Hyd' in x):                        simple.append('Hydrophobe')
  if ('Don' in x) and ('$hDon' not in x): simple.append('Donor')
  if ('Acc' in x) and ('$hAcc' not in x): simple.append('Acceptor')
  if ('Cat' in x) and ('$hCat' not in x): simple.append('PosIonizable') # Priority to Don over Cat
  if ('Ani' in x) and ('$hAni' not in x): simple.append('NegIonizable') # Priority to Acc over Ani
  return simple

features_df['rdkit_family'] = features_df['type'].apply(rdkit_type)
feat_coords = features_df[['x','y','z']].to_numpy()
feat_r = features_df['radius'].to_numpy() + args.pad
feat_fam = features_df['rdkit_family'].copy()

mols = Chem.SDMolSupplier(args.sdf, removeHs=False)

mol_to_features = {}

fdef = os.path.join(RDConfig.RDDataDir, "BaseFeatures.fdef")
feat_factory = ChemicalFeatures.BuildFeatureFactory(fdef)

for mol_i, mol in enumerate(mols):
  feats = feat_factory.GetFeaturesForMol(mol)
  # build family list for each atom
  atom_fam = [[] for _ in range(mol.GetNumAtoms())]

  for f in feats:
    fam = f.GetFamily()
    for aidx in f.GetAtomIds():
      atom_fam[aidx].append(fam)

  conf = mol.GetConformer() # need to initialize conf
  atom_coords = np.array([[conf.GetAtomPosition(a.GetIdx()).x,
                           conf.GetAtomPosition(a.GetIdx()).y,
                           conf.GetAtomPosition(a.GetIdx()).z]
                          for a in mol.GetAtoms()])

  # distance matrix: atoms x features
  dists = np.linalg.norm(atom_coords[:,None,:]-feat_coords[None,:,:], axis=2)
  hits = []
  # loop only over atoms (features stay vectorized)
  for i, atom_types in enumerate(atom_fam):
    if len(atom_types) == 0: # skip atoms with no features
      continue

    # find ANY matches between feature "family(s)" of atoms and silcs ph4 features
    # NOTE: this means that 'Donor' will match ['Donor','PosIonizable']
    type_match = np.array([any(t in ff for t in atom_types) for ff in feat_fam])
    # within that feature's radius
    radius_match = dists[i] <= feat_r
    good = np.where(type_match & radius_match)[0]
    hits.extend(good)

  #mol_to_features[mol_i] = np.array(hits)
  mol_to_features[mol_i] = set(hits)

feature_counts = Counter()
for s in mol_to_features.values():
  feature_counts.update(s)

fig,((ax0,ax1),(ax2,ax3)) = plt.subplots(2,2, figsize=(8,6), width_ratios=[4,2], sharey='row')
ax3.axis('off')

center_str = open(args.center_txt).read().strip()
center = np.array([float(i) for i in center_str.split(',')])

features_df['dist'] = np.linalg.norm(features_df[['x','y','z']].to_numpy()-center, axis=1)

# Histogram of the number of molecules which have each feature
all_feats = np.array(list(feature_counts.elements()))  # number of molecules with each feature
counts, bars = np.histogram(all_feats, bins=range(features_df.shape[0]+1))
ax0.bar(features_df.index, counts, color=c[0])
ax0.set_ylabel("# Molecules", fontweight="bold")
ax0.grid()
ax0.axhline(y=len(mols),color='k', linestyle='--')

# Histogram of the number of molecules which have each hypothesis
hypotheses_counts = Counter(frozenset(int(i) for i in s) for s in mol_to_features.values() if len(s) > 2)

hypotheses = [list(k) for k in hypotheses_counts.keys()]
counts = list(hypotheses_counts.values())

ax1.bar(range(len(counts)), counts, color=c[0])
ax1.set_xticks(range(len(counts)), hypotheses, rotation=70)
ax1.set_xlabel("Hypothesis", fontweight="bold")
#ax1.set_ylabel("# Molecules", fontweight="bold")
ax1.grid()

# plot FGFE and distance
ax2.sharex(ax0)
ax2t = ax2.twinx()
ax2.bar(features_df.index, features_df['dist'], color=c[0], alpha=0.5)
ax2.set_ylabel(r"Distance $\bf{(\AA)}$", fontweight="bold")
ax2t.bar(features_df.index, features_df['FGFE'], color=c[1], alpha=0.5)
ax2t.set_ylabel("FGFE (kcal/mol)", fontweight="bold")
ax2.set_xlabel("Feature Index", fontweight="bold")
ax2.grid()
ax2.set_xticks(features_df.index, [int(b) for b in features_df.index])

# Show or quiet
plt.tight_layout()
plt.savefig('histogram.svg')
if not args.quiet: plt.show()

count_name=0
for i,h in enumerate(hypotheses):
  if args.n_feat:
    if len(h) == args.n_feat:
      print(h)
      count_name+=1
  else:
    if len(h) > 2:
      print(h)
      count_name+=1
      #write_ph4(f"{args.out}/{str(count_name).zfill(int(1+np.log10(len(hypotheses))))}.ph4", features_df.iloc[h])
