#!/usr/bin/env python
#
import argparse
import pandas as pd
import numpy as np
from scipy.spatial.distance import cdist
from scipy.special import expit
import itertools

def parse_ph4(filename, features_dat=None):
  feature_rows = []

  n_features = None
  reading_features = False
  features_read = 0

  with open(filename, 'r') as f:
    for line in f:
      stripped = line.strip()

      # all the initial lines before #feature is read are part of the header
      if stripped.startswith("#feature"):
        parts = stripped.split()
        n_features = int(parts[1])
        reading_features = True
        continue

      if reading_features and features_read < n_features:
        if not stripped or stripped.startswith("#"): continue

        parts = stripped.split()
        # based on example format
        feature_rows.append({
          "type": parts[0],
          "color": parts[1],
          "x": float(parts[2]),
          "y": float(parts[3]),
          "z": float(parts[4]),
          "radius": float(parts[5]),
          "ebits": int(parts[6]),
          "gbits": int(parts[7]),
        })
        features_read += 1

      if reading_features and features_read == n_features: break

  features_df = pd.DataFrame(feature_rows)

  if features_dat:
    # Read in <prot>.features.dat file with the FGFE for each feature
    # Type | Sphere Center X | Y | Z | Sphere radius R | FGFE

    feat_dat = pd.read_csv(features_dat, sep='\\s+', skiprows=2, names=['type','x','y','z','radius','FGFE'])
    for c in ['x','y','z']: 
      feat_dat[c] = feat_dat[c].round(4) 
      features_df[c] = features_df[c].round(4)
    cols = ['x', 'y', 'z']

    merged = features_df.merge(feat_dat[cols + ['FGFE']], on=cols, how='left')
    features_df['FGFE'] = merged['FGFE'].round(4)
 
  return features_df

def load_hypotheses_txt(filename):
  lists = []
  with open(filename) as f:
    for line in f:
      lists.append(eval(line.strip()))
  return lists

def write_ph4(filename, features_df):
  n_features = str(features_df.shape[0])
  header = [
  "#moe:ph4que 2011.1\n",
  "#SILCS pharmacophore hypothesis generated by ph4gen utility\n",
  "#pharmacophore 5 tag t value *\n",
  f"scheme t Unified matchsize i  {n_features} title t $ comment s $ smask i 476156\n",
  f"#feature {n_features} expr tt color ix x r y r z r r r ebits ix gbits ix\n"
  ]

  with open(filename, "w") as f:
    # write header as-is
    for line in header:
      f.write(line)
    # write features
    for _, row in features_df.iterrows():
      f.write(
        f"{row['type']:12s} "
        f"{row['color']:6s} "
        f"{row['x']:10.4f} "
        f"{row['y']:10.4f} "
        f"{row['z']:10.4f} "
        f"{row['radius']:6.3f} "
        f"{int(row['ebits'])} "
        f"{int(row['gbits'])}\n"
      )
    f.write("#endpharmacophore\n")

def enumerate_hypotheses(features_df, center):
  indices = features_df.index
  aro_hyd_indices = features_df[features_df['type'] == 'Aro|Hyd'].index
  hypotheses = np.array(list(itertools.combinations(indices, N_feat)))
  return hypotheses

def analyze_hypotheses(features_df, center, n_feat, core, exclude):
  indices = features_df.index
  # NOTE: $m is & or "AND"; $m$h is &! or "AND NOT"
  aro_hyd_indices = features_df[(features_df['type'].str.contains('Aro|Hyd', regex=True))].index
  don_indices = features_df[(features_df['type'].str.contains('Don')) & ~ (features_df['type'].str.contains('$hDon'))].index
  acc_indices = features_df[(features_df['type'].str.contains('Acc')) & ~ (features_df['type'].str.contains('$hAcc'))].index
  cat_indices = features_df[(features_df['type'].str.contains('Cat')) & ~ (features_df['type'].str.contains('$hCat'))].index
  ani_indices = features_df[(features_df['type'].str.contains('Ani')) & ~ (features_df['type'].str.contains('$hAni'))].index

  # Enumeration of combinations
  hypotheses = np.array(list(itertools.combinations(indices, n_feat)))

  # Properties
  points = features_df[['x','y','z']].to_numpy()
  dist = np.linalg.norm(points-center, axis=1)
  mutual_dist = cdist(points, points)
  # Counts
  aro_count = np.isin(hypotheses, aro_hyd_indices).sum(axis=1)
  don_count = np.isin(hypotheses, don_indices).sum(axis=1)
  acc_count = np.isin(hypotheses, acc_indices).sum(axis=1)
  hb_count  = np.isin(hypotheses, don_indices).sum(axis=1) + np.isin(hypotheses, acc_indices).sum(axis=1)
  ani_count = np.isin(hypotheses, ani_indices).sum(axis=1)
  cat_count = np.isin(hypotheses, cat_indices).sum(axis=1)
  # Distances
  centroid_dist = np.array([np.linalg.norm(points[idx_list].mean(axis=0)-center) for idx_list in hypotheses])
  mean_separation = np.array([mutual_dist[idx_list].mean() for idx_list in hypotheses])
  max_dist = np.array([dist[idx_list].max() for idx_list in hypotheses])
  min_dist = np.array([dist[idx_list].min() for idx_list in hypotheses])
  mean_dist = np.array([dist[idx_list].mean() for idx_list in hypotheses])
  # P(harm)GFE = sum of F(eature)GFE
  fgfe = features_df['FGFE'].to_numpy()
  pgfe = np.array([fgfe[idx_list].sum() for idx_list in hypotheses])

  df = pd.DataFrame({
  "hypothesis": list(hypotheses),
  "PGFE": pgfe,
  "aro_count": aro_count,
  "acc_count":acc_count,
  "don_count":don_count,
  "hb_count": hb_count,
  "ani_count": ani_count,
  "cat_count": cat_count,
  "max_dist": max_dist,
  "min_dist": min_dist,
  "mean_dist": mean_dist,
  "mean_separation": mean_separation,
  "centroid_dist": centroid_dist
  })

  # Identify if hypothesis contains certain core features
  core_set = set(core)
  mask_core = np.array([core_set <= set(map(int, h)) for h in hypotheses])

  # excluded features
  if len(exclude) > 0:
    mask_exclude = np.array([any(e in h for e in exclude) for h in hypotheses])
  else:
    mask_exclude = np.zeros(len(hypotheses), dtype=bool)
  
  mask_keep = mask_core & ~mask_exclude
  df = df[mask_keep]
  
  df["hypothesis_list"] = df["hypothesis"].apply(lambda h: [int(hi) for hi in h])
  df["hypothesis_set"]  = df["hypothesis"].apply(lambda h: set([int(hi) for hi in h]))
  df['core'] = [core]*len(df)

  return df

def multiple_hypotheses_lengths(features_df, center, nlist=[4,5], core=np.array([]), exclude=np.array([])):
  all_df = pd.DataFrame()
  for nfeat in nlist:
    df = analyze_hypotheses(features_df, center, n_feat=nfeat, core=core, exclude=exclude)
    all_df = pd.concat([all_df, df])
  return all_df

def select_top_k(group, k=20, prefer="small"):
  df = group.copy()
  df["set"] = df["hypothesis_set"]

  df = df.sort_values("score", ascending=False).reset_index(drop=True)

  sets = list(df["set"])

  accepted = list(range(k))
  candidate = k

  def is_duplicate(a, b):
    return a >= b or b >= a

  changed = True
  while changed:
    changed = False

    for pos_i, i in enumerate(accepted):
      for pos_j, j in enumerate(accepted[pos_i + 1:], start=pos_i + 1):

        if not is_duplicate(sets[i], sets[j]):
          continue

        # choose which one to keep
        if prefer == "small":
          keep = i if len(sets[i]) <= len(sets[j]) else j
        else:
          keep = i if len(sets[i]) >= len(sets[j]) else j

        replace_pos = pos_j if keep == i else pos_i

        # find next valid candidate
        while candidate < len(df):
          new_set = sets[candidate]

          if all(
            not is_duplicate(new_set, sets[idx])
            for idx in accepted
            if idx != accepted[replace_pos]
          ):
            accepted[replace_pos] = candidate
            candidate += 1
            changed = True
            break

          candidate += 1

        if changed:
          break

      if changed:
        break

  df["keep"] = False
  df.loc[accepted, "keep"] = True

  return df

def predict_score(df, topk, prefer):
  df_score = df.copy()
  df_score['nPGFE'] = (df_score['PGFE'] + 53)/35 ## Standardize PGFE; mean=-53, std=35
  x_features = ['nPGFE','aro_count', 'acc_count', 'don_count', 'ani_count', 'cat_count', 'max_dist']
  X = df_score[x_features].to_numpy()

  coef = np.array([-2.00, 4.00, 6.00, -5.00, -4.00, 7.00, -2.00])
  intercept = -1
  df_score['score'] = expit(X @ coef + intercept)
  df_score = select_top_k(df_score, topk, prefer=prefer)
  df_score = df_score.reset_index()
  return df_score

def main():
  parser = argparse.ArgumentParser(prog='ph4gen.py', description='Automatically generate pharmacophore hypotheses from supplied input file containing many pharmacophore features. MOE ph4 pharmacophore files are supported.', epilog='The set of pharmacophore hypotheses are generated using left-padded numbers.')
  parser.add_argument('-i', '--input',  required=True,  help='Input ph4 (MOE-format) file')
  parser.add_argument('-f', '--features', required=True,  help='Input features.dat (SILCS-format) file')
  parser.add_argument(      '--hypotheses', required=False, help='Input txt file containing hypotheses as comma-separated integers (features)')
  parser.add_argument(      '--core',                   help='(Optional) Indices of desired features. NOTE: Indices start from 0')
  parser.add_argument(      '--exclude',                   help='(Optional) Indices of features to be excluded. NOTE: Indices start from 0')
  parser.add_argument(      '--center',                 help='(Optional) Cordinates of binding site: x,y,z; if not supplied, calculated from feature distribution')
  parser.add_argument(      '--nfeat', default="4,5",   help='(Optional) Number(s) of features per hypotheses: 4,5 ; default=%(default)s')
  parser.add_argument(      '--topk',    type=int,   default=20,     help="Top k hypotheses to be selected; default=%(default)s")
  #parser.add_argument('-d', '--distance_cutoff', default=10.0, type=float, help='(Optional) Distance cutoff of features (Ang); default=%(default)s')
  parser.add_argument('-p', '--prefix', required=False, help='(Optional) Prefix of output ph4 (MOE-format) file')
  parser.add_argument(      '--prefer', required=False, default='small', help='(Optional) Prefer small or large hypotheses')
  args = parser.parse_args()

  # Get all pharmacophore features
  features_df = parse_ph4(args.input, features_dat=args.features)
  
  if args.center: 
    center = np.array([float(i) for i in args.center.split(',')])
  else:
    print('--center not provided; center of features will be used.')
    center = features_df[['x','y','z']].to_numpy().mean(axis=0)

  core = np.array([])
  if args.core: core = np.array([int(i) for i in args.core.split(',')])
  exclude=np.array([])
  if args.exclude: exclude = np.array([int(i) for i in args.exclude.split(',')])

  if not args.hypotheses:
    print(f'Scoring mode will output {args.topk} hypotheses of length {args.nfeat}')
    # todo: deal with nfeat options
    
    nlist = [int(i) for i in args.nfeat.split(',')]
    df = multiple_hypotheses_lengths(features_df, center, nlist=nlist, core=core, exclude=exclude)
    #for nfeat in nlist if not args.n_feat else [args.n_feat]:
    scores_df = predict_score(df, args.topk, args.prefer)
    print(scores_df[scores_df['keep']][['score','hypothesis']].head(args.topk))
    hypotheses = scores_df[scores_df['keep']]['hypothesis']
  else:
    hypotheses = load_hypotheses_txt(args.hypotheses)
  
  # Write out hypotheses
  for h in hypotheses:
    if len(h) > 2:
      name=''
      for f in h:
        name+=f"{f}_"
      if args.prefix:
        write_ph4(f"{args.prefix}{name[:-1]}.ph4", features_df.iloc[h])
      else:
        write_ph4(f"{name[:-1]}.ph4", features_df.iloc[h])

if __name__ == "__main__":
  main()
